/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Evernote.EDAM.NoteStore
{

  #if !SILVERLIGHT && !NETFX_CORE
  [Serializable]
  #endif
  public partial class AdParameters : TBase
  {
    private string _clientLanguage;
    private List<AdImpressions> _impressions;
    private bool _supportHtml;
    private Dictionary<string, string> _clientProperties;

    public string ClientLanguage
    {
      get
      {
        return _clientLanguage;
      }
      set
      {
        __isset.clientLanguage = true;
        this._clientLanguage = value;
      }
    }

    public List<AdImpressions> Impressions
    {
      get
      {
        return _impressions;
      }
      set
      {
        __isset.impressions = true;
        this._impressions = value;
      }
    }

    public bool SupportHtml
    {
      get
      {
        return _supportHtml;
      }
      set
      {
        __isset.supportHtml = true;
        this._supportHtml = value;
      }
    }

    public Dictionary<string, string> ClientProperties
    {
      get
      {
        return _clientProperties;
      }
      set
      {
        __isset.clientProperties = true;
        this._clientProperties = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT && !NETFX_CORE
    [Serializable]
    #endif
    public struct Isset {
      public bool clientLanguage;
      public bool impressions;
      public bool supportHtml;
      public bool clientProperties;
    }

    public AdParameters() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 2:
            if (field.Type == TType.String) {
              ClientLanguage = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.List) {
              {
                Impressions = new List<AdImpressions>();
                TList _list86 = iprot.ReadListBegin();
                for( int _i87 = 0; _i87 < _list86.Count; ++_i87)
                {
                  AdImpressions _elem88 = new AdImpressions();
                  _elem88 = new AdImpressions();
                  _elem88.Read(iprot);
                  Impressions.Add(_elem88);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.Bool) {
              SupportHtml = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.Map) {
              {
                ClientProperties = new Dictionary<string, string>();
                TMap _map89 = iprot.ReadMapBegin();
                for( int _i90 = 0; _i90 < _map89.Count; ++_i90)
                {
                  string _key91;
                  string _val92;
                  _key91 = iprot.ReadString();
                  _val92 = iprot.ReadString();
                  ClientProperties[_key91] = _val92;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("AdParameters");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ClientLanguage != null && __isset.clientLanguage) {
        field.Name = "clientLanguage";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ClientLanguage);
        oprot.WriteFieldEnd();
      }
      if (Impressions != null && __isset.impressions) {
        field.Name = "impressions";
        field.Type = TType.List;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Impressions.Count));
          foreach (AdImpressions _iter93 in Impressions)
          {
            _iter93.Write(oprot);
            oprot.WriteListEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.supportHtml) {
        field.Name = "supportHtml";
        field.Type = TType.Bool;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(SupportHtml);
        oprot.WriteFieldEnd();
      }
      if (ClientProperties != null && __isset.clientProperties) {
        field.Name = "clientProperties";
        field.Type = TType.Map;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.String, TType.String, ClientProperties.Count));
          foreach (string _iter94 in ClientProperties.Keys)
          {
            oprot.WriteString(_iter94);
            oprot.WriteString(ClientProperties[_iter94]);
            oprot.WriteMapEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("AdParameters(");
      sb.Append("ClientLanguage: ");
      sb.Append(ClientLanguage);
      sb.Append(",Impressions: ");
      sb.Append(Impressions);
      sb.Append(",SupportHtml: ");
      sb.Append(SupportHtml);
      sb.Append(",ClientProperties: ");
      sb.Append(ClientProperties);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
