/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Evernote.EDAM.NoteStore
{

  /// <summary>
  /// Captures a collection of share relationships for a single note,
  /// for example, as returned by the getNoteShares method. The share
  /// relationships fall into two broad categories: members, and
  /// invitations that can be used to become members.
  /// 
  /// <dl>
  /// <dt>invitations</dt>
  /// <dd>A list of open invitations that can be redeemed into
  /// memberships to the note.</dd>
  /// 
  /// <dt>memberships</dt>
  /// <dd>A list of memberships of the noteb. A member is identified
  /// by their Evernote UserID and has rights to access the
  /// note.</dd>
  /// 
  /// <dt>restrictions</dt>
  /// <dd>The restrictions on which privileges may be assigned to the recipient
  /// of an open invitation. These restrictions only apply to invitations;
  /// restrictions on memberships are specified on the NoteMemberShareRelationship.
  /// This field is used by the service to convey information to the user, so
  /// clients should treat it as read-only.</dd>
  /// 
  /// </dl>
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class NoteShareRelationships : TBase
  {
    private List<NoteInvitationShareRelationship> _invitations;
    private List<NoteMemberShareRelationship> _memberships;
    private NoteShareRelationshipRestrictions _invitationRestrictions;

    public List<NoteInvitationShareRelationship> Invitations
    {
      get
      {
        return _invitations;
      }
      set
      {
        __isset.invitations = true;
        this._invitations = value;
      }
    }

    public List<NoteMemberShareRelationship> Memberships
    {
      get
      {
        return _memberships;
      }
      set
      {
        __isset.memberships = true;
        this._memberships = value;
      }
    }

    public NoteShareRelationshipRestrictions InvitationRestrictions
    {
      get
      {
        return _invitationRestrictions;
      }
      set
      {
        __isset.invitationRestrictions = true;
        this._invitationRestrictions = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool invitations;
      public bool memberships;
      public bool invitationRestrictions;
    }

    public NoteShareRelationships() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List) {
                {
                  Invitations = new List<NoteInvitationShareRelationship>();
                  TList _list162 = iprot.ReadListBegin();
                  for( int _i163 = 0; _i163 < _list162.Count; ++_i163)
                  {
                    NoteInvitationShareRelationship _elem164;
                    _elem164 = new NoteInvitationShareRelationship();
                    _elem164.Read(iprot);
                    Invitations.Add(_elem164);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.List) {
                {
                  Memberships = new List<NoteMemberShareRelationship>();
                  TList _list165 = iprot.ReadListBegin();
                  for( int _i166 = 0; _i166 < _list165.Count; ++_i166)
                  {
                    NoteMemberShareRelationship _elem167;
                    _elem167 = new NoteMemberShareRelationship();
                    _elem167.Read(iprot);
                    Memberships.Add(_elem167);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Struct) {
                InvitationRestrictions = new NoteShareRelationshipRestrictions();
                InvitationRestrictions.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("NoteShareRelationships");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Invitations != null && __isset.invitations) {
          field.Name = "invitations";
          field.Type = TType.List;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, Invitations.Count));
            foreach (NoteInvitationShareRelationship _iter168 in Invitations)
            {
              _iter168.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (Memberships != null && __isset.memberships) {
          field.Name = "memberships";
          field.Type = TType.List;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, Memberships.Count));
            foreach (NoteMemberShareRelationship _iter169 in Memberships)
            {
              _iter169.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (InvitationRestrictions != null && __isset.invitationRestrictions) {
          field.Name = "invitationRestrictions";
          field.Type = TType.Struct;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          InvitationRestrictions.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("NoteShareRelationships(");
      bool __first = true;
      if (Invitations != null && __isset.invitations) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Invitations: ");
        __sb.Append(Invitations);
      }
      if (Memberships != null && __isset.memberships) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Memberships: ");
        __sb.Append(Memberships);
      }
      if (InvitationRestrictions != null && __isset.invitationRestrictions) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("InvitationRestrictions: ");
        __sb.Append(InvitationRestrictions== null ? "<null>" : InvitationRestrictions.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
