/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Evernote.EDAM.NoteStore
{
  /// <summary>
  /// Privilege levels for accessing shared notebooks.
  /// 
  /// READ_NOTEBOOK: Recipient is able to read the contents of the shared notebook
  ///   but does not have access to information about other recipients of the
  ///   notebook or the activity stream information.
  /// 
  /// READ_NOTEBOOK_PLUS_ACTIVITY: Recipient has READ_NOTEBOOK rights and can also
  ///   access information about other recipients and the activity stream.
  /// 
  /// MODIFY_NOTEBOOK_PLUS_ACTIVITY: Recipient has rights to read and modify the contents
  ///   of the shared notebook, including the right to move notes to the trash and to create
  ///   notes in the notebook.  The recipient can also access information about other
  ///   recipients and the activity stream.
  /// 
  /// FULL_ACCESS: Recipient has full rights to the shared notebook and recipient lists,
  ///   including privilege to revoke and create invitations and to change privilege
  ///   levels on invitations for individuals. If the user is a member of the same group,
  ///   (e.g. the same business) as the shared notebook, they will additionally be granted
  ///   permissions to update the publishing status of the notebook.
  /// </summary>
  public enum ShareRelationshipPrivilegeLevel
  {
    READ_NOTEBOOK = 0,
    READ_NOTEBOOK_PLUS_ACTIVITY = 10,
    MODIFY_NOTEBOOK_PLUS_ACTIVITY = 20,
    FULL_ACCESS = 30,
  }
}
