/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Evernote.EDAM.Type
{
  /// <summary>
  /// This enumeration defines the possible types of canMoveToContainer outcomes.
  /// <p />
  /// An outdated client is expected to signal a "Cannot Move, Please Upgrade To Learn Why"
  /// like response to the user if an unknown enumeration value is received.
  /// <dl>
  /// <dt>CAN_BE_MOVED</dt>
  /// <dd>Can move Notebook to Workspace.</dd>
  /// <dt>INSUFFICIENT_ENTITY_PRIVILEGE</dt>
  /// <dd>Can not move Notebook to Workspace, because either:
  ///  a) Notebook not in Workspace and insufficient privilege on Notebook
  ///  or b) Notebook in Workspace and membership on Workspace with insufficient privilege
  ///  for move</dd>
  /// <dt>INSUFFICIENT_CONTAINER_PRIVILEGE</dt>
  /// <dd>Notebook in Workspace and no membership on Workspace.
  /// </dd>
  /// </dl>
  /// </summary>
  public enum CanMoveToContainerStatus
  {
    CAN_BE_MOVED = 1,
    INSUFFICIENT_ENTITY_PRIVILEGE = 2,
    INSUFFICIENT_CONTAINER_PRIVILEGE = 3,
  }
}
