/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Evernote.EDAM.Type
{
  /// <summary>
  /// Every search query is specified as a sequence of characters.
  /// Currently, only the USER query format is supported.
  /// </summary>
  public enum QueryFormat
  {
    USER = 1,
    SEXP = 2,
  }
}
