/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace Evernote.EDAM.Type
{
  public enum QueryFormat
  {
    USER = 1,
    SEXP = 2,
  }
}
