/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Evernote.EDAM.Type
{
  /// <summary>
  /// An enumeration describing the configuration state related to receiving
  /// reminder e-mails from the service.  Reminder e-mails summarize notes
  /// based on their Note.attributes.reminderTime values.
  /// 
  /// DO_NOT_SEND: The user has selected to not receive reminder e-mail.
  /// 
  /// SEND_DAILY_EMAIL: The user has selected to receive reminder e-mail for those
  ///   days when there is a reminder.
  /// </summary>
  public enum ReminderEmailConfig
  {
    DO_NOT_SEND = 1,
    SEND_DAILY_EMAIL = 2,
  }
}
