/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Evernote.EDAM.Type
{
  /// <summary>
  /// This enumeration defines the possible tiers of service that a user may have. A
  /// ServiceLevel of BUSINESS signifies a business-only account, which can never be any
  /// other ServiceLevel.
  /// </summary>
  public enum ServiceLevel
  {
    BASIC = 1,
    PLUS = 2,
    PREMIUM = 3,
    BUSINESS = 4,
  }
}
