/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Evernote.EDAM.Type
{

  /// <summary>
  /// Settings meant for the recipient of a shared notebook, such as
  /// for indicating which types of notifications the recipient wishes
  /// for reminders, etc.
  /// 
  /// The reminderNotifyEmail and reminderNotifyInApp fields have a
  /// 3-state read value but a 2-state write value.  On read, it is
  /// possible to observe "unset", true, or false.  The initial state is
  /// "unset".  When you choose to set a value, you may set it to either
  /// true or false, but you cannot unset the value.  Once one of these
  /// members has a true/false value, it will always have a true/false
  /// value.
  /// 
  /// <dl>
  /// <dt>reminderNotifyEmail</dt>
  /// <dd>Indicates that the user wishes to receive daily e-mail notifications
  ///     for reminders associated with the notebook. This may be true only for
  ///     business notebooks that belong to the business of which the user is a
  ///     member. You may only set this value on a notebook in your business.</dd>
  /// <dt>reminderNotifyInApp</dt>
  /// <dd>Indicates that the user wishes to receive notifications for
  ///     reminders by applications that support providing such
  ///     notifications.  The exact nature of the notification is defined
  ///     by the individual applications.</dd>
  /// </dl>
  /// 
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SharedNotebookRecipientSettings : TBase
  {
    private bool _reminderNotifyEmail;
    private bool _reminderNotifyInApp;

    public bool ReminderNotifyEmail
    {
      get
      {
        return _reminderNotifyEmail;
      }
      set
      {
        __isset.reminderNotifyEmail = true;
        this._reminderNotifyEmail = value;
      }
    }

    public bool ReminderNotifyInApp
    {
      get
      {
        return _reminderNotifyInApp;
      }
      set
      {
        __isset.reminderNotifyInApp = true;
        this._reminderNotifyInApp = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool reminderNotifyEmail;
      public bool reminderNotifyInApp;
    }

    public SharedNotebookRecipientSettings() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Bool) {
                ReminderNotifyEmail = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Bool) {
                ReminderNotifyInApp = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("SharedNotebookRecipientSettings");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.reminderNotifyEmail) {
          field.Name = "reminderNotifyEmail";
          field.Type = TType.Bool;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(ReminderNotifyEmail);
          oprot.WriteFieldEnd();
        }
        if (__isset.reminderNotifyInApp) {
          field.Name = "reminderNotifyInApp";
          field.Type = TType.Bool;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(ReminderNotifyInApp);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("SharedNotebookRecipientSettings(");
      bool __first = true;
      if (__isset.reminderNotifyEmail) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ReminderNotifyEmail: ");
        __sb.Append(ReminderNotifyEmail);
      }
      if (__isset.reminderNotifyInApp) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ReminderNotifyInApp: ");
        __sb.Append(ReminderNotifyInApp);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
