/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Evernote.EDAM.Type
{
  /// <summary>
  /// Enumeration of the roles that a User can have within a sponsored group.
  /// 
  /// GROUP_MEMBER: The user is a member of the group with no special privileges.
  /// 
  /// GROUP_ADMIN: The user is an administrator within the group.
  /// 
  /// GROUP_OWNER: The user is the owner of the group.
  /// </summary>
  public enum SponsoredGroupRole
  {
    GROUP_MEMBER = 1,
    GROUP_ADMIN = 2,
    GROUP_OWNER = 3,
  }
}
