/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Evernote.EDAM.Type
{
  /// <summary>
  /// 
  /// </summary>
  public enum UserIdentityType
  {
    EVERNOTE_USERID = 1,
    EMAIL = 2,
    IDENTITYID = 3,
  }
}
